projectName: hello-apollo
applicationName: hello-apollo
pipelineRef: nodejs-pipeline
manifestGitUrl: ssh://git@github.com/dgipjn/ocp-manifests.git
enabledLintSonar: true
ignoreLinterFailures: true
ignoreTestFailures: true
ignoreScanFailures: true
ignoreQualityGate: true
enabledCompile: true
useModulesCache: false
nodejsImage: image-registry.openshift-image-registry.svc:5000/openshift/nodejs:18-ubi8


